### ISSUE TITLE
Release and license it!

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/TableWriter#1]
It would be good to get this released so I can depend on an artifact rather than copy pasting all the classes. There are a bunch of steps [here](http://central.sonatype.org/pages/ossrh-guide.html) and you can copy what I did if you like for adding license headers and configuring the release plugin.

**Comment by tjheslin1** [comment]
Cool. Thanks I'll get on it!

**Comment by tjheslin1** [comment]
Making good progress on this!

**Comment by tjheslin1** [comment]
```
<dependency>
    <groupId>io.github.tjheslin1</groupId>
    <artifactId>TableWriter</
    <version>1.1</version>
</dependency>
```
