### ISSUE TITLE
Add a method to print to a String

### ISSUE THREAD

**Issue by theangrydev** [tjheslin1/TableWriter#2]

**Comment by tjheslin1** [comment]
I agree. Not everyone may want to provide an _OutputStrategy_. I'll add another method where you can just take the formatted table as a string.

**Comment by tjheslin1** [comment]
This has been done, you can see the commit [here](https://github.com/tjheslin1/TableWriter/commit/bcf6fedc3eedd5c1200936eae2eff9d56b2f0a1f). Added a method `tableAsString()` to TableLogger.
